version: '3.8'

services:
  db:
    image: postgres:12.2-alpine
    container_name: "postgres12.2"
    ports:
      - "5432:5432"
    tty: true
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    image: todo-app:1.0
    container_name: "todo-api"
    tty: true
    env_file:
      - .env
    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SSL_MODE: ${SSL_MODE}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:


networks:
  fullstack:
    driver: bridge
